config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: Settings.numbers.maximum_50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.numbers.maximum_255},
    format: {with: VALID_EMAIL_REGEX}, 
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: Settings.numbers.minimum_6}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
      update remember_digest: User.digest(remember_token)
    end

    def authenticated? remember_token
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
      update remember_digest: nil
    end

    def current_user? user
      user == current_user
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
  if user && user.authenticate(params[:session][:password])
    log_in user
    params[:session][:remember_me] == "1" ? remember(user) : forget(user)
    redirect_to user  
    else
      flash.now[:danger] = t ".invalid_mail_pass"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
  
  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id] 
    return if @user
    flash[:danger] = t ".fail"
    redirect_to root_path
  end

  def index; end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t ".welcome"
      redirect_to @user
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated? :remember, cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.numbers.size_80
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %> <%=link_to t(".base_title"), Settings.links.link2 %>
    <%= t ".by" %> <%=link_to t(".michael_hartl"), Settings.links.link1 %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><%= link_to t(".news"), Settings.links.link3 %></li>
    </ul>
  </nav>
</footer

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/contact.html.erb
<% provide :title, t(".contact_header") %>
<h1> <%= t ".contact_header" %> </h1>
<p>
  <%= t ".contact" %>
  <%= link_to t(".contact_pages"), Settings.links.link3 %>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %><%= pluralize @user.errors.count, t(".err") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t(".about_header") %>
<h1><%= t ".about_header" %> </h1>
<p>
  <%= t ".the" %> <%= link_to t(".base_title"), Settings.links.link4 %> <%= t ".is" %>
  <%= link_to t(".book"), Settings.links.link5 %> <%= t".and" %>
  <%= link_to t(".screencast_series"), Settings.links.link6 %> <%= t".to" %>
  <%= link_to t(".ror"), Settings.links.link7 %>
  <%= t ".this" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".contact1") %>
<h1><%= t ".contact_header" %></h1>
<p>
  <%= t ".contact" %>
  <%= link_to t(".contact_page"), Settings.links.link3 %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".help_header") %>
<h1><%= t ".help_header" %></h1>
<p>
  <%= t ".get" %>
  <%= link_to t(".ror_help"), Settings.links.link8 %>
  <%= t ".to" %>
  <%= link_to t(".base_title"), Settings.links.link5 %>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".welcome_header" %></h1>
  <h2>
    <%= t ".this_header" %>
    <%= link_to t(".ror"), Settings.links.link2 %>
    <%= t ".sample" %>
  </h2>
  <%= link_to t(".sign_up") , signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: t(".logo")), Settings.links.link2 %>

app/views/users/index.html.erb
index.html.erb

app/views/users/new.html.erb
<% provide :title, t(".signup") %>
<h1><%= t ".signup" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t ".create_my_account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>